### ISSUE TITLE
Document doesn't define what is a virtual organisation

### ISSUE THREAD

**Issue by paulmillar** [WLCG-AuthZ-WG/common-jwt-profile#38]
The document makes rather extensive uses the abbreviation "VO" (and related terms, like "VO-centric" and "VO-admin") when defining expected behaviour.

There are two problems here:
  * (rather trivially) the document never identifies that this VO abbreviation is short for "virtual organisation".
  * (more significantly) the document never defines what *is* VO.  It tacitly assumes that the reader already knows this.

The second point is much more worrying.  Without a concrete definition of the term, it is open to different interpretations.  Different readers, with different experiences or use-cases in mind, may draw different conclusions on whether something is or isn't a VO.

**Comment by maarten-litmaath** [comment]
Please check #47 that is proposed to supersede #41 .

**Comment by maarten-litmaath** [comment]
Resolved by #47 .
