### ISSUE TITLE
Inconsistency in token issuer public key cache lifetimes

### ISSUE THREAD

**Issue by DrDaveD** [WLCG-AuthZ-WG/common-jwt-profile#52]
#17 modified a table to say the maximum token issuer public key cache lifetime is 4 days, but there is another section of text that is inconsistent with that.   The [Token Verification](https://github.com/WLCG-AuthZ-WG/common-jwt-profile/blob/81dfcdf4e94708fcafb4fd2bc14ebf8829532023/profile.md#token-verification) section says
```
The recommended lifetime of the public key cache is one day, but SHOULD be kept to less than 7 days. 
```

**Comment by maarten-litmaath** [comment]
To be fixed indeed.  I also think the example URLs in that section should not be clickable...
